# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-01 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='keywords',
            field=models.TextField(null=True),
        ),
    ]
